In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import classification_report
import joblib

print("pandas version:", pd.__version__)
print("numpy version:", np.__version__)
print("matplotlib version:", matplotlib.__version__)  # Access __version__ from matplotlib

pandas version: 2.3.3
numpy version: 2.3.4
matplotlib version: 3.10.7


In [10]:
# Local file paths - replace Google Colab paths
# Note: Google Drive integration only works in Google Colab environment
# For local usage, we use relative paths to dataset folder

# Dataset

rekap-volunter-28-agustus.csv

In [11]:
data_path_vle = "dataset/rekap-volunter-28-agustus.csv.xlsx - rekap-volunter-28-agustus.csv"
df_rekap_volunteer = pd.read_csv(data_path_vle)
df_rekap_volunteer.head()

NAMA            NAMA_DEPT           npm  \
0            Abi Rizki Hidayat     Sistem Informasi  882006580948   
1   Abimantrana Agra Prartana        Bisnis Digital   81246862329   
2                Achmad Sahlan  Teknologi Informasi  882006661211   
3  Adinda Rizkya Putri Wibawa       Ilmu Komunikasi   82220754285   
4      ADITYA SAPUTRA DARMAWAN     Sistem Informasi   82241354470   

   time_materi_video  time_materi_dokumen  time_materi_artikel  time_task  \
0               1199                 7461                 5262       9016   
1              10051                21252                11170         65   
2               7520                 1155                  607         98   
3                190                 5352                 1940          5   
4                 68                  145                  183         10   

   time_quiz  time_material  time_forum  total_time      time  
0          0          13922           5       36865  10:14:25  
1          0          42473           0       85011  23:36:51  
2          0           9282           0       18662   5:11:02  
3          0           7482           0       14969   4:09:29  
4          0            396           0         802   0:13:22

dfjadi.csv

In [12]:
data_path_vle = "dataset/dfjadi-simplified - dfjadi-simplified.csv"
df_jadi = pd.read_csv(data_path_vle)
df_jadi.head()

NIM                                Nama Jenis Kelamin  \
0  22SA11A074               Mohamad Ridho Mubarok     Laki-laki   
1  22SA11A134  Maria Angelina Cahyani Candrakasih     Perempuan   
2  22SA31A027        Tresnanda Agsifa Cakra Buana     Laki-laki   
3  22sa11a038          Ndaru Febrian Pujo Leksono     Laki-laki   
4  22SA11A035              Nurul Khotimah Ansyari     Perempuan   

                 Prodi  Skor 1  Skor 2  Skor 3  Skor 4        Pemrosesan  \
0          Informatika      -1       1      -3      -3  Reflektif Rendah   
1          Informatika       1      -3      -5       1      Aktif Rendah   
2  Teknologi Informasi      -5       5       1       1  Reflektif Sedang   
3          Informatika      -1       1      -7      -3  Reflektif Rendah   
4          Informatika      -5      -1      -5       3  Reflektif Sedang   

          Persepsi          Input          Pemahaman  
0   Sensing Rendah  Verbal Rendah      Global Rendah  
1  Intuitif Rendah  Verbal Sedang  Sequential Rendah  
2   Sensing Sedang  Visual Rendah  Sequential Rendah  
3   Sensing Rendah  Verbal Sedang      Global Rendah  
4  Intuitif Rendah  Verbal Sedang  Sequential Rendah

rekap.csv

In [13]:
data_path_vle = "dataset/rekap-001.csv"
df_rekap = pd.read_csv(data_path_vle)
df_rekap.head()

NPM               NAMA  time_materials  time_tasks  time_forums  \
0    MHS001  Mahasiswa Pertama               0           0            0   
1  21SA1090              Bobit               0           0            5   
2  MHSIF001     Mahasiswa IF 1           19636        1009         2959   
3  MHSIF002     Mahasiswa IF 2               0           0            0   
4  MHSIF003     Mahasiswa IF 3               0           0            0   

   time_quizzes  
0             0  
1             0  
2             0  
3             0  
4             0

In [14]:
df_jadi_selected = df_jadi[["NIM", "Pemrosesan", "Persepsi", "Input", "Pemahaman"]]

df_merged = pd.merge(
    df_rekap,
    df_jadi_selected,
    left_on="NPM",
    right_on="NIM",
    how="left"   # atau "inner" tergantung kebutuhan
)
df_merged.head(10)

NPM               NAMA  time_materials  time_tasks  time_forums  \
0    MHS001  Mahasiswa Pertama               0           0            0   
1  21SA1090              Bobit               0           0            5   
2  MHSIF001     Mahasiswa IF 1           19636        1009         2959   
3  MHSIF002     Mahasiswa IF 2               0           0            0   
4  MHSIF003     Mahasiswa IF 3               0           0            0   
5  MHSIF004     Mahasiswa IF 4               0           0            0   
6  MHSIF005     Mahasiswa IF 5               0           0            0   
7  MHSIF006     Mahasiswa IF 6               0           0            0   
8  MHSIF007     Mahasiswa IF 7               0          10            0   
9  MHSIF008     Mahasiswa IF 8               0           0            0   

   time_quizzes  NIM Pemrosesan Persepsi Input Pemahaman  
0             0  NaN        NaN      NaN   NaN       NaN  
1             0  NaN        NaN      NaN   NaN       NaN  
2             0  NaN        NaN      NaN   NaN       NaN  
3             0  NaN        NaN      NaN   NaN       NaN  
4             0  NaN        NaN      NaN   NaN       NaN  
5             0  NaN        NaN      NaN   NaN       NaN  
6             0  NaN        NaN      NaN   NaN       NaN  
7             0  NaN        NaN      NaN   NaN       NaN  
8             0  NaN        NaN      NaN   NaN       NaN  
9             0  NaN        NaN      NaN   NaN       NaN

In [15]:
df_jadi.to_csv("output.csv", index=False)

In [16]:
df_jadi.sort_values('NIM')

NIM                  Nama Jenis Kelamin                Prodi  Skor 1  \
464    -  Malvino Abel Calvero     Laki-laki          Informatika      -1   
449    -                 Azhar     Laki-laki      Ilmu Komunikasi      -3   
460    -              akbar dr     Laki-laki          Informatika       1   
459    -         Reghina salwa     Perempuan          Informatika      -5   
447    -         Tutur hidayah     Laki-laki          Informatika      -1   
..   ...                   ...           ...                  ...     ...   
455    _       panji suwarsono     Laki-laki          Informatika      -1   
451    d    Dina reksa Saputri     Perempuan      Ilmu Komunikasi      -3   
130  tes                   tes     Laki-laki          Informatika      -1   
437    y      Rizki nur rahman     Laki-laki      Ilmu Komunikasi      -1   
461    ~   Herfian ades satria     Laki-laki  Teknologi Informasi       1   

     Skor 2  Skor 3  Skor 4        Pemrosesan         Persepsi          Input  \
464      -3      -5      -3  Reflektif Rendah  Intuitif Rendah  Verbal Sedang   
449       5      -3      -1  Reflektif Rendah   Sensing Sedang  Verbal Rendah   
460      -3      -3       1      Aktif Rendah  Intuitif Rendah  Verbal Rendah   
459      -1      -5      -1  Reflektif Sedang  Intuitif Rendah  Verbal Sedang   
447      -1       3      -3  Reflektif Rendah  Intuitif Rendah  Visual Rendah   
..      ...     ...     ...               ...              ...            ...   
455       1       1       3  Reflektif Rendah   Sensing Rendah  Visual Rendah   
451      -5      -1      -1  Reflektif Rendah  Intuitif Sedang  Verbal Rendah   
130      -3      -3      -1  Reflektif Rendah  Intuitif Rendah  Verbal Rendah   
437       3      -1      -1  Reflektif Rendah   Sensing Rendah  Verbal Rendah   
461       1       5       3      Aktif Rendah   Sensing Rendah  Visual Sedang   

             Pemahaman  
464      Global Rendah  
449      Global Rendah  
460  Sequential Rendah  
459      Global Rendah  
447      Global Rendah  
..                 ...  
455  Sequential Rendah  
451      Global Rendah  
130      Global Rendah  
437      Global Rendah  
461  Sequential Rendah  

[604 rows x 12 columns]

In [17]:
df_rekap.loc[98]

NPM                     MHSBD007
NAMA              Mahasiswa BD 7
time_materials                 0
time_tasks                     0
time_forums                    0
time_quizzes                   0
Name: 98, dtype: object

# Explorasi dfjadi

In [18]:
data_path_vle = "dataset/dfjadi-simplified - dfjadi-simplified.csv"
df_jadi = pd.read_csv(data_path_vle)
df_jadi.head()

NIM                                Nama Jenis Kelamin  \
0  22SA11A074               Mohamad Ridho Mubarok     Laki-laki   
1  22SA11A134  Maria Angelina Cahyani Candrakasih     Perempuan   
2  22SA31A027        Tresnanda Agsifa Cakra Buana     Laki-laki   
3  22sa11a038          Ndaru Febrian Pujo Leksono     Laki-laki   
4  22SA11A035              Nurul Khotimah Ansyari     Perempuan   

                 Prodi  Skor 1  Skor 2  Skor 3  Skor 4        Pemrosesan  \
0          Informatika      -1       1      -3      -3  Reflektif Rendah   
1          Informatika       1      -3      -5       1      Aktif Rendah   
2  Teknologi Informasi      -5       5       1       1  Reflektif Sedang   
3          Informatika      -1       1      -7      -3  Reflektif Rendah   
4          Informatika      -5      -1      -5       3  Reflektif Sedang   

          Persepsi          Input          Pemahaman  
0   Sensing Rendah  Verbal Rendah      Global Rendah  
1  Intuitif Rendah  Verbal Sedang  Sequential Rendah  
2   Sensing Sedang  Visual Rendah  Sequential Rendah  
3   Sensing Rendah  Verbal Sedang      Global Rendah  
4  Intuitif Rendah  Verbal Sedang  Sequential Rendah

In [19]:
df_start_with_21 = df_jadi[df_jadi['NIM'].astype(str).str.startswith('21')]
# df_start_with_21.head()
df_start_with_21.NIM.count()

np.int64(15)

In [20]:
df_start_with_22 = df_jadi[df_jadi['NIM'].astype(str).str.startswith('22')]
# df_start_with_22.head()
df_start_with_22.NIM.count()

np.int64(150)

In [21]:
df_start_with_23 = df_jadi[df_jadi['NIM'].astype(str).str.startswith('23')]
# df_start_with_23.head()
df_start_with_23.NIM.count()

np.int64(252)

In [22]:
df_start_with_24 = df_jadi[df_jadi['NIM'].astype(str).str.startswith('24')]
# df_start_with_24.head()
df_start_with_24.NIM.count()

np.int64(146)

In [23]:
df_jadi.NIM.count()

np.int64(604)

In [24]:
df_jadi.NIM.count() - (df_start_with_21.NIM.count() + df_start_with_22.NIM.count() + df_start_with_23.NIM.count() + df_start_with_24.NIM.count())

np.int64(41)

In [25]:
df_merged_years = pd.concat([df_start_with_21, df_start_with_22, df_start_with_23, df_start_with_24])
# display(df_merged_years.head())
df_merged_years.NIM.count()

np.int64(563)

In [26]:
df_merged_years.head()

NIM                   Nama Jenis Kelamin           Prodi  Skor 1  \
136  21SA1194     Rizky Aulia Rahman     Laki-laki     Informatika      -1   
168  21SA1086  Muhammad Thoriq Jamil     Laki-laki     Informatika      -3   
171  21SA1158   Velizha Sandy Kusuma     Perempuan     Informatika      -3   
173  21SA1220        Aldona Septiana     Perempuan     Informatika      -5   
217  21SB1022    Refita Dwi Nurjanah     Perempuan  Bisnis Digital       1   

     Skor 2  Skor 3  Skor 4        Pemrosesan         Persepsi          Input  \
136       5      -5      -7  Reflektif Rendah   Sensing Sedang  Verbal Sedang   
168       7      -3       1  Reflektif Rendah   Sensing Sedang  Verbal Rendah   
171      -5       1      -3  Reflektif Rendah  Intuitif Sedang  Visual Rendah   
173      -1      -1      -3  Reflektif Sedang  Intuitif Rendah  Verbal Rendah   
217      -1      -5      -1      Aktif Rendah  Intuitif Rendah  Verbal Sedang   

             Pemahaman  
136      Global Sedang  
168  Sequential Rendah  
171      Global Rendah  
173      Global Rendah  
217      Global Rendah

In [27]:
df_merged_years['Pemrosesan'].isna().sum()

np.int64(0)

In [28]:
df_merged_years.to_csv("df_merged_years_output.csv", index=False)

# Explorasi Mahasiswa Spend Time

In [29]:
data_path_vle = "dataset/rekap-001.csv"
df_rekap = pd.read_csv(data_path_vle)
df_rekap.head()

NPM               NAMA  time_materials  time_tasks  time_forums  \
0    MHS001  Mahasiswa Pertama               0           0            0   
1  21SA1090              Bobit               0           0            5   
2  MHSIF001     Mahasiswa IF 1           19636        1009         2959   
3  MHSIF002     Mahasiswa IF 2               0           0            0   
4  MHSIF003     Mahasiswa IF 3               0           0            0   

   time_quizzes  
0             0  
1             0  
2             0  
3             0  
4             0

In [30]:
df_rekap.NPM.count()

np.int64(456)

# Dataset

In [31]:
df_merged_years = df_jadi[["NIM", "Nama", "Pemrosesan", "Persepsi", "Input", "Pemahaman"]]

df_merged = pd.merge(
    df_merged_years,
    df_rekap,
    left_on="NIM",
    right_on="NPM",
    how="left"   # atau "inner" tergantung kebutuhan
)
df_merged.head()

NIM                                Nama        Pemrosesan  \
0  22SA11A074               Mohamad Ridho Mubarok  Reflektif Rendah   
1  22SA11A134  Maria Angelina Cahyani Candrakasih      Aktif Rendah   
2  22SA31A027        Tresnanda Agsifa Cakra Buana  Reflektif Sedang   
3  22sa11a038          Ndaru Febrian Pujo Leksono  Reflektif Rendah   
4  22SA11A035              Nurul Khotimah Ansyari  Reflektif Sedang   

          Persepsi          Input          Pemahaman  NPM NAMA  \
0   Sensing Rendah  Verbal Rendah      Global Rendah  NaN  NaN   
1  Intuitif Rendah  Verbal Sedang  Sequential Rendah  NaN  NaN   
2   Sensing Sedang  Visual Rendah  Sequential Rendah  NaN  NaN   
3   Sensing Rendah  Verbal Sedang      Global Rendah  NaN  NaN   
4  Intuitif Rendah  Verbal Sedang  Sequential Rendah  NaN  NaN   

   time_materials  time_tasks  time_forums  time_quizzes  
0             NaN         NaN          NaN           NaN  
1             NaN         NaN          NaN           NaN  
2             NaN         NaN          NaN           NaN  
3             NaN         NaN          NaN           NaN  
4             NaN         NaN          NaN           NaN

In [32]:
df_merged.NPM.count()

np.int64(123)

In [33]:
df_merged['Pemrosesan'].isna().sum()

np.int64(0)

In [34]:
df_merged['Pemrosesan'].notna().sum()

np.int64(604)

In [35]:
df_merged.Pemrosesan.nunique()

5

In [36]:
df_merged.Pemrosesan.unique()

array(['Reflektif Rendah', 'Aktif Rendah', 'Reflektif Sedang',
       'Reflektif Kuat', 'Aktif Sedang'], dtype=object)

In [37]:
df_merged.Input.unique()

array(['Verbal Rendah', 'Verbal Sedang', 'Visual Rendah', 'Visual Sedang',
       'Verbal Kuat'], dtype=object)

In [38]:
df_merged.Input.nunique()

5

In [39]:
# Pemrosesan: Refrektif, Aktif
# Persepsi: Visual, Verbal

In [40]:
def map_pemrosesan(row):
    if (row['Pemrosesan'] == 'Reflektif Kuat') or (row['Pemrosesan'] == 'Reflektif Sedang') or (row['Pemrosesan'] == 'Reflektif Rendah'):
        return 'Reflektif'
    elif (row['Pemrosesan'] == 'Aktif Kuat') or (row['Pemrosesan'] == 'Aktif Sedang') or (row['Pemrosesan'] == 'Aktif Rendah'):
        return 'Aktif'
    else:
        return None

def map_input(row):
    if (row['Input'] == 'Visual Kuat') or (row['Input'] == 'Visual Sedang') or (row['Input'] == 'Visual Rendah'):
        return 'Visual'
    elif (row['Input'] == 'Verbal Kuat') or (row['Input'] == 'Verbal Sedang') or (row['Input'] == 'Verbal Rendah'):
        return 'Verbal'
    else:
        return None

# Tambahkan kolom baru
df_merged['Pemrosesan'] = df_merged.apply(map_pemrosesan, axis=1)
df_merged['Input'] = df_merged.apply(map_input, axis=1)


In [41]:
df_merged.head()

NIM                                Nama Pemrosesan         Persepsi  \
0  22SA11A074               Mohamad Ridho Mubarok  Reflektif   Sensing Rendah   
1  22SA11A134  Maria Angelina Cahyani Candrakasih      Aktif  Intuitif Rendah   
2  22SA31A027        Tresnanda Agsifa Cakra Buana  Reflektif   Sensing Sedang   
3  22sa11a038          Ndaru Febrian Pujo Leksono  Reflektif   Sensing Rendah   
4  22SA11A035              Nurul Khotimah Ansyari  Reflektif  Intuitif Rendah   

    Input          Pemahaman  NPM NAMA  time_materials  time_tasks  \
0  Verbal      Global Rendah  NaN  NaN             NaN         NaN   
1  Verbal  Sequential Rendah  NaN  NaN             NaN         NaN   
2  Visual  Sequential Rendah  NaN  NaN             NaN         NaN   
3  Verbal      Global Rendah  NaN  NaN             NaN         NaN   
4  Verbal  Sequential Rendah  NaN  NaN             NaN         NaN   

   time_forums  time_quizzes  
0          NaN           NaN  
1          NaN           NaN  
2          NaN           NaN  
3          NaN           NaN  
4          NaN           NaN

In [42]:
# df_merged.to_csv("df_merged_output.csv", index=False)

In [43]:
df_merged.columns.tolist()

['NIM',
 'Nama',
 'Pemrosesan',
 'Persepsi',
 'Input',
 'Pemahaman',
 'NPM',
 'NAMA',
 'time_materials',
 'time_tasks',
 'time_forums',
 'time_quizzes']

In [44]:
df_merged_simplified = df_merged[[
    'NIM',
    'NAMA',
    'time_materials',
    'time_tasks',
    'time_forums',
    'time_quizzes',
    'Pemrosesan',
    'Input',
    ]].copy()

In [45]:
df_merged_simplified.head()

NIM NAMA  time_materials  time_tasks  time_forums  time_quizzes  \
0  22SA11A074  NaN             NaN         NaN          NaN           NaN   
1  22SA11A134  NaN             NaN         NaN          NaN           NaN   
2  22SA31A027  NaN             NaN         NaN          NaN           NaN   
3  22sa11a038  NaN             NaN         NaN          NaN           NaN   
4  22SA11A035  NaN             NaN         NaN          NaN           NaN   

  Pemrosesan   Input  
0  Reflektif  Verbal  
1      Aktif  Verbal  
2  Reflektif  Visual  
3  Reflektif  Verbal  
4  Reflektif  Verbal

In [46]:
df_merged_simplified['NAMA'].notna().sum()

np.int64(123)

In [47]:
df_merged_simplified_not_null =  df_merged_simplified[df_merged_simplified['NAMA'].notna()]
df_merged_simplified_not_null['NIM'].count()

np.int64(123)

In [48]:
df_merged_simplified_not_null.head()

NIM                   NAMA  time_materials  time_tasks  \
16  23SA21A011          IWAN HARYATNO         49555.0      7610.0   
24  23SA11A045  REFIDA SEPTIANA PUTRI         36562.0         0.0   
29  22SA11A027      WISNU PRATAMA AJI             0.0         0.0   
31  22SA11A289                MAHMUDI         14060.0         0.0   
36  22SA11A097    ADITYA OKTA SAPUTRA          2071.0         0.0   

    time_forums  time_quizzes Pemrosesan   Input  
16          5.0           0.0      Aktif  Visual  
24          0.0           0.0  Reflektif  Verbal  
29          0.0           0.0  Reflektif  Visual  
31          0.0           0.0  Reflektif  Verbal  
36          0.0           0.0  Reflektif  Verbal

## One Hot Encoding

In [49]:
df_merged_simplified_not_null['labels'] = df_merged_simplified_not_null[['Pemrosesan', 'Input']].values.tolist()

/tmp/ipykernel_19669/1202623539.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged_simplified_not_null['labels'] = df_merged_simplified_not_null[['Pemrosesan', 'Input']].values.tolist()


In [50]:
df_merged_simplified_not_null.head()

NIM                   NAMA  time_materials  time_tasks  \
16  23SA21A011          IWAN HARYATNO         49555.0      7610.0   
24  23SA11A045  REFIDA SEPTIANA PUTRI         36562.0         0.0   
29  22SA11A027      WISNU PRATAMA AJI             0.0         0.0   
31  22SA11A289                MAHMUDI         14060.0         0.0   
36  22SA11A097    ADITYA OKTA SAPUTRA          2071.0         0.0   

    time_forums  time_quizzes Pemrosesan   Input               labels  
16          5.0           0.0      Aktif  Visual      [Aktif, Visual]  
24          0.0           0.0  Reflektif  Verbal  [Reflektif, Verbal]  
29          0.0           0.0  Reflektif  Visual  [Reflektif, Visual]  
31          0.0           0.0  Reflektif  Verbal  [Reflektif, Verbal]  
36          0.0           0.0  Reflektif  Verbal  [Reflektif, Verbal]

In [51]:
df_merged_simplified_not_null = df_merged_simplified_not_null.drop(columns=['NIM', 'NAMA', 'Pemrosesan', 'Input'])
df_merged_simplified_not_null.head()

time_materials  time_tasks  time_forums  time_quizzes               labels
16         49555.0      7610.0          5.0           0.0      [Aktif, Visual]
24         36562.0         0.0          0.0           0.0  [Reflektif, Verbal]
29             0.0         0.0          0.0           0.0  [Reflektif, Visual]
31         14060.0         0.0          0.0           0.0  [Reflektif, Verbal]
36          2071.0         0.0          0.0           0.0  [Reflektif, Verbal]

In [52]:
df_merged_simplified_not_null.to_csv("df_merged_simplified_not_null_output.csv", index=False)

In [53]:
mlb = MultiLabelBinarizer()
y = mlb.fit_transform(df_merged_simplified_not_null["labels"])
X = df_merged_simplified_not_null.drop(columns=["labels"])

print("Label classes:", mlb.classes_)
print("Encoded labels:\n", y)

Label classes: ['Aktif' 'Reflektif' 'Verbal' 'Visual']
Encoded labels:
 [[1 0 0 1]
 [0 1 1 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [1 0 1 0]
 [1 0 0 1]
 [0 1 1 0]
 [0 1 0 1]
 [0 1 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [1 0 1 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [1 0 1 0]
 [0 1 0 1]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 1 0]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 0 1]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 

# Training

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [55]:
# 4️⃣ Model Random Forest + MultiOutput wrapper
base_model = RandomForestClassifier(n_estimators=100, random_state=42)
multi_label_model = MultiOutputClassifier(base_model)
multi_label_model.fit(X_train, y_train)

# 5️⃣ Prediksi dan evaluasi
y_pred = multi_label_model.predict(X_test)
print(classification_report(y_test, y_pred, target_names=mlb.classes_))

              precision    recall  f1-score   support

       Aktif       0.50      0.10      0.17        10
   Reflektif       0.74      0.96      0.84        27
      Verbal       0.85      0.90      0.88        31
      Visual       0.25      0.17      0.20         6

   micro avg       0.76      0.76      0.76        74
   macro avg       0.59      0.53      0.52        74
weighted avg       0.71      0.76      0.71        74
 samples avg       0.76      0.76      0.76        74



# Save

In [56]:
# Simpan model
joblib.dump(multi_label_model, "multi_label_model.pkl")

# Simpan juga encoder label
joblib.dump(mlb, "label_encoder.pkl")

['label_encoder.pkl']

# Load

In [57]:
# Load kembali model dan encoder
multi_label_model = joblib.load("multi_label_model.pkl")
mlb = joblib.load("label_encoder.pkl")

# Contoh input baru
X_new = [[7510.0,	0.0,	5.0,	0.0]]

# Prediksi
y_pred = multi_label_model.predict(X_new)

# Konversi hasil kembali ke label asli
decoded_labels = mlb.inverse_transform(y_pred)
print(decoded_labels)


[('Reflektif', 'Verbal')]


/home/didi/Documents/skripsi/klasifikasi-model/myenv/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/didi/Documents/skripsi/klasifikasi-model/myenv/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/didi/Documents/skripsi/klasifikasi-model/myenv/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/home/didi/Documents/skripsi/klasifikasi-model/myenv/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
